import { random } from './random'

export function randomPhrase(length = 4) {
  const words = [
    'large',
    'boorish',
    'skinny',
    'pumped',
    'competitive',
    'fancy',
    'difficult',
    'swanky',
    'groomed',
    'fragile',
    'dirty',
    'obvious',
    'deeply',
    'pushy',
    'zany',
    'dynamic',
    'wiry',
    'satisfying',
    'parched',
    'enchanted',
    'fluttering',
    'three',
    'poised',
    'knotty',
    'guilty',
    'sedate',
    'unusual',
    'magnificent',
    'woozy',
    'shiny',
    'adjoining',
    'harmonious',
    'ratty',
    'bitter',
    'loud',
    'accurate',
    'elegant',
    'frequent',
    'selfish',
    'truculent',
    'absent',
    'plucky',
    'majestic',
    'yummy',
    'overjoyed',
    'handsome',
    'detailed',
    'flung',
    'probable',
    'wasteful'
  ]
  return Array.from({ length })
    .map(() => words.splice(random(words.length - 1), 1))
    .join('-')
}
